// <auto-generated />
using System;
using Cercel_Roxana_Madalina_Proiect_Restaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cercel_Roxana_Madalina_Proiect_Restaurant.Migrations
{
    [DbContext(typeof(Cercel_Roxana_Madalina_Proiect_RestaurantContext))]
    partial class Cercel_Roxana_Madalina_Proiect_RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Angajat", b =>
                {
                    b.Property<int>("AngajatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NrTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OreSupl")
                        .HasColumnType("int");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("AngajatId");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varsta")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Meniu", b =>
                {
                    b.Property<int>("MeniuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gramaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("MeniuID");

                    b.ToTable("Meniu");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.MeniuProdus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MeniuID")
                        .HasColumnType("int");

                    b.Property<int>("ProdusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MeniuID");

                    b.HasIndex("ProdusID");

                    b.ToTable("MeniuProdus");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProdusNume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Rezervare", b =>
                {
                    b.Property<int>("RezervareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OraData")
                        .HasColumnType("datetime2");

                    b.HasKey("RezervareID");

                    b.HasIndex("ClientID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.MeniuProdus", b =>
                {
                    b.HasOne("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Meniu", "Meniu")
                        .WithMany("MeniuProduse")
                        .HasForeignKey("MeniuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Produs", "Produs")
                        .WithMany("MeniuProduse")
                        .HasForeignKey("ProdusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meniu");

                    b.Navigation("Produs");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Rezervare", b =>
                {
                    b.HasOne("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Client", "Client")
                        .WithMany("Rezervarile")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Client", b =>
                {
                    b.Navigation("Rezervarile");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Meniu", b =>
                {
                    b.Navigation("MeniuProduse");
                });

            modelBuilder.Entity("Cercel_Roxana_Madalina_Proiect_Restaurant.Models.Produs", b =>
                {
                    b.Navigation("MeniuProduse");
                });
#pragma warning restore 612, 618
        }
    }
}
